(:package asl-browser-plugin
 :version "1.0.0"
 :entry "src/plugin.asl"
 :description "Aslany Browser Plugin: Voice-In Action-Out, In-Tab WebGPU, AudioWorklet 16kHz & AXTree Perception"
 :asl-first true
 :dependencies [])
